In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2220, 9407, 2118, 2167],
 [2220, 9407, 2118, 769],
 [2220, 1976, 2118, 6186],
 [8685, 48, 3132, 5463, 7205],
 [8685, 48, 3132, 5463, 9640],
 [5903, 2220, 7313, 2118, 2546],
 [8186, 9794, 6633, 5463]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2220 9407 2118 2167]
 [   0    0    0    0 2220 9407 2118  769]
 [   0    0    0    0 2220 1976 2118 6186]
 [   0    0    0 8685   48 3132 5463 7205]
 [   0    0    0 8685   48 3132 5463 9640]
 [   0    0    0 5903 2220 7313 2118 2546]
 [   0    0    0    0 8186 9794 6633 5463]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

2025-09-03 10:07:25.981863: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-09-03 10:07:25.981939: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-09-03 10:07:25.981968: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-09-03 10:07:25.982085: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-09-03 10:07:25.982215: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

2025-09-03 10:07:29.527235: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 0s 306ms/step


array([[[ 4.36205789e-03, -3.50644439e-03,  2.04115547e-02,
          2.18454115e-02, -2.68918518e-02, -1.05901584e-02,
         -4.14725654e-02,  3.46700586e-02,  1.15868337e-02,
          4.74192984e-02],
        [ 4.36205789e-03, -3.50644439e-03,  2.04115547e-02,
          2.18454115e-02, -2.68918518e-02, -1.05901584e-02,
         -4.14725654e-02,  3.46700586e-02,  1.15868337e-02,
          4.74192984e-02],
        [ 4.36205789e-03, -3.50644439e-03,  2.04115547e-02,
          2.18454115e-02, -2.68918518e-02, -1.05901584e-02,
         -4.14725654e-02,  3.46700586e-02,  1.15868337e-02,
          4.74192984e-02],
        [ 4.36205789e-03, -3.50644439e-03,  2.04115547e-02,
          2.18454115e-02, -2.68918518e-02, -1.05901584e-02,
         -4.14725654e-02,  3.46700586e-02,  1.15868337e-02,
          4.74192984e-02],
        [-3.36566716e-02,  3.00259516e-03, -2.68337131e-02,
          4.77811433e-02, -2.03290824e-02, -2.11796891e-02,
         -1.63758621e-02,  1.42373107e-02,  3.548033

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2220, 9407, 2118, 2167], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 153ms/step


array([[ 0.00436206, -0.00350644,  0.02041155,  0.02184541, -0.02689185,
        -0.01059016, -0.04147257,  0.03467006,  0.01158683,  0.0474193 ],
       [ 0.00436206, -0.00350644,  0.02041155,  0.02184541, -0.02689185,
        -0.01059016, -0.04147257,  0.03467006,  0.01158683,  0.0474193 ],
       [ 0.00436206, -0.00350644,  0.02041155,  0.02184541, -0.02689185,
        -0.01059016, -0.04147257,  0.03467006,  0.01158683,  0.0474193 ],
       [ 0.00436206, -0.00350644,  0.02041155,  0.02184541, -0.02689185,
        -0.01059016, -0.04147257,  0.03467006,  0.01158683,  0.0474193 ],
       [-0.03365667,  0.0030026 , -0.02683371,  0.04778114, -0.02032908,
        -0.02117969, -0.01637586,  0.01423731,  0.03548033, -0.00425667],
       [-0.01806552,  0.00573604,  0.0027158 , -0.00565364, -0.02001926,
        -0.02604122,  0.01290205,  0.02589932, -0.02820733, -0.02739058],
       [ 0.03475099, -0.03928519,  0.02593109,  0.00710789, -0.03096328,
         0.01044623,  0.01758682, -0.0346867 